/*
        Liste des Departements Francais.
 */
export class Departement {
    public departement            = [
        { value: '01', display: 'Ain - Bourg-en-bresse' },
        { value: '02', display: 'Aisne - Laon' },
        { value: '03', display: 'Allier - Moulins' },
        { value: '04', display: 'Alpes-de-Haute-Provence - Digne-les-bains' },
        { value: '05', display: 'Hautes-alpes - Gap' },
        { value: '06', display: 'Alpes-maritimes - Nice' },
        { value: '07', display: 'Ardèche - Privas' },
        { value: '08', display: 'Ardennes - Charleville-mézières' },
        { value: '09', display: 'Ariège - Foix' },
        { value: '10', display: 'Aube - Troyes' },
        { value: '11', display: 'Aude - Carcassonne' },
        { value: '12', display: 'Aveyron - Rodez' },
        { value: '13', display: 'Bouches-du-Rhône - Marseille' },
        { value: '14', display: 'Calvados - Caen' },
        { value: '15', display: 'Cantal - Aurillac' },
        { value: '16', display: 'Charente - Angoulême' },
        { value: '17', display: 'Charente-maritime - La rochelle' },
        { value: '18', display: 'Cher - Bourges' },
        { value: '19', display: 'Corrèze - Tulle' },
        { value: '2A', display: 'Corse-du-sud - Ajaccio' },
        { value: '2B', display: 'Haute-Corse - Bastia' },
        { value: '21', display: 'Côte-d\'Or - Dijon' },
        { value: '22', display: 'Côtes-d\'Armor - Saint-brieuc' },
        { value: '23', display: 'Creuse - Guéret' },
        { value: '24', display: 'Dordogne - Périgueux' },
        { value: '25', display: 'Doubs - Besançon' },
        { value: '26', display: 'Drôme - Valence' },
        { value: '27', display: 'Eure - Évreux' },
        { value: '28', display: 'Eure-et-loir - Chartres' },
        { value: '29', display: 'Finistère - Quimper' },
        { value: '30', display: 'Gard - Nîmes' },
        { value: '31', display: 'Haute-garonne - Toulouse' },
        { value: '32', display: 'Gers - Auch' },
        { value: '33', display: 'Gironde - Bordeaux' },
        { value: '34', display: 'Hérault - Montpellier' },
        { value: '35', display: 'Ille-et-vilaine - Rennes' },
        { value: '36', display: 'Indre - Châteauroux' },
        { value: '37', display: 'Indre-et-loire - Tours' },
        { value: '38', display: 'Isère - Grenoble' },
        { value: '39', display: 'Jura - Lons-le-saunier' },
        { value: '40', display: 'Landes - Mont-de-marsan' },
        { value: '41', display: 'Loir-et-cher - Blois' },
        { value: '42', display: 'Loire - Saint-étienne' },
        { value: '43', display: 'Haute-loire - Le puy-en-velay' },
        { value: '44', display: 'Loire-atlantique - Nantes' },
        { value: '45', display: 'Loiret - Orléans' },
        { value: '46', display: 'Lot - Cahors' },
        { value: '47', display: 'Lot-et-garonne - Agen' },
        { value: '48', display: 'Lozère - Mende' },
        { value: '49', display: 'Maine-et-loire - Angers' },
        { value: '50', display: 'Manche - Saint-lô' },
        { value: '51', display: 'Marne - Châlons-en-champagne' },
        { value: '52', display: 'Haute-marne - Chaumont' },
        { value: '53', display: 'Mayenne - Laval' },
        { value: '54', display: 'Meurthe-et-moselle - Nancy' },
        { value: '55', display: 'Meuse - Bar-le-duc' },
        { value: '56', display: 'Morbihan - Vannes' },
        { value: '57', display: 'Moselle - Metz' },
        { value: '58', display: 'Nièvre - Nevers' },
        { value: '59', display: 'Nord - Lille' },
        { value: '60', display: 'Oise - Beauvais' },
        { value: '61', display: 'Orne - Alençon' },
        { value: '62', display: 'Pas-de-calais - Arras' },
        { value: '63', display: 'Puy-de-dôme - Clermont-ferrand' },
        { value: '64', display: 'Pyrénées-atlantiques - Pau' },
        { value: '65', display: 'Hautes-Pyrénées - Tarbes' },
        { value: '66', display: 'Pyrénées-orientales - Perpignan' },
        { value: '67', display: 'Bas-rhin - Strasbourg' },
        { value: '68', display: 'Haut-rhin - Colmar' },
        { value: '69', display: 'Rhône - Lyon' },
        { value: '70', display: 'Haute-saône - Vesoul' },
        { value: '71', display: 'Saône-et-loire - Mâcon' },
        { value: '72', display: 'Sarthe - Le mans' },
        { value: '73', display: 'Savoie - Chambéry' },
        { value: '74', display: 'Haute-savoie - Annecy' },
        { value: '75', display: 'Paris - Paris' },
        { value: '76', display: 'Seine-maritime - Rouen' },
        { value: '77', display: 'Seine-et-marne - Melun' },
        { value: '78', display: 'Yvelines - Versailles' },
        { value: '79', display: 'Deux-sèvres - Niort' },
        { value: '80', display: 'Somme - Amiens' },
        { value: '81', display: 'Tarn - Albi' },
        { value: '82', display: 'Tarn-et-garonne - Montauban' },
        { value: '83', display: 'Var - Toulon' },
        { value: '84', display: 'Vaucluse - Avignon' },
        { value: '85', display: 'Vendée - La roche-sur-yon' },
        { value: '86', display: 'Vienne - Poitiers' },
        { value: '87', display: 'Haute-vienne - Limoges' },
        { value: '88', display: 'Vosges - Épinal' },
        { value: '89', display: 'Yonne - Auxerre' },
        { value: '90', display: 'Territoire de belfort - Belfort' },
        { value: '91', display: 'Essonne - Évry' },
        { value: '92', display: 'Hauts-de-seine - Nanterre' },
        { value: '93', display: 'Seine-Saint-Denis - Bobigny' },
        { value: '94', display: 'Val-de-marne - Créteil' },
        { value: '95', display: 'Val-d\'oise - Pontoise' },
        { value: '971', display: 'Guadeloupe - Basse-terre' },
        { value: '972', display: 'Martinique - Fort-de-france' },
        { value: '973', display: 'Guyane - Cayenne' },
        { value: '974', display: 'La réunion - Saint-denis' },
        { value: '976', display: 'Mayotte - Dzaoudzi' },
        { value: '999', display: 'Hors France.' }
    ];
}